#!/bin/bash

#0COLORES BASICOS: 0;30 - 37
negro="\e[0;30m"
rojo="\e[0;31m"
verde="\e[0;32m"
amarillo="\e[0;33m"
azul="\e[0;34m"
morado="\e[0;35m"
celeste="\e[0;36m"
blanco="\e[0;37m"

#1COLORES BASICOS NEGRITA: 1;30 - 37
bnegro="\e[1;30m"
brojo="\e[1;31m"
bverde="\e[1;32m"
bamarillo="\e[1;33m"
bazul="\e[1;34m"
bmorado="\e[1;35m"
bceleste="\e[1;36m"
bblanco="\e[1;37m"

#2COLORES BASICOS FONDO: 40 - 47
fnegro="\e[40m"
frojo="\e[41m"
fverde="\e[42m"
famarillo="\e[43m"
fazul="\e[44m"
fmorado="\e[45m"
fceleste="\e[46m"
fblanco="\e[47m"

#3COLORES BASICOS SUBRAYADO: 4;30 -37
snegro="\e[4;30m"
srojo="\e[4;31m"
sverde="\e[4;32m"
samarillo="\e[4;33m"
sazul="\e[4;34m"
smorado="\e[4;35m"
sceleste="\e[4;36m"
sblanco="\e[4;37m"

#4COLORES BASICOS ALTA INTENSIDAD: 0;90 - 97
hnegro="\e[0;90m"
hrojo="\e[0;91m"
hverde="\e[0;92m"
hamarillo="\e[0;93m"
hazul="\e[0;94m"
hmorado="\e[0;95m"
hceleste="\e[0;96m"
hblanco="\e[0;97m"

#5COLORES BASICOS NEGRITA ALTA INTENSIDAD: 1;90 - 97
nhnegro="\e[1;90m"
nhrojo="\e[1;91m"
nhverde="\e[1;92m"
nhamarillo="\e[1;93m"
nhazul="\e[1;94m"
nhmorado="\e[1;95m"
nhceleste="\e[1;96m"
nhblanco="\e[1;97m"

#6COLORES BASICOS FONDO ALTA INTENSIDAD: 0,100 - 107
fhnegro="\e[0;100m"
fhrojo="\e[0;101m"
fhverde="\e[0;102m"
fhamarillo="\e[0;103m"
fhazul="\e[0;104m"
fhmorado="\e[0;105m"
fhceleste="\e[0;106m"
fhblanco="\e[0;107m"

#7COLORES BASICOS FONDO ALTA INTENSIDAD TEXTO NEGRITA: 1,100 - 107
fnhnegro='\e[1;100m' # NEGRO
fnhrojo='\e[1;101m' # ROJO
fnhverde='\e[1;102m' # VERDE
fnhamarillo='\e[1;103m' # AMARILLO
fnhazul='\e[1;104m' # AZUL
fnhmorado='\e[1;105m' # MORADO
fnhceleste='\e[1;106m' # CELESTE
fnhblanco='\e[1;107m' # BLANCO

#reset color
resetc="\e[0m"

# ejemplos:
# Mensaje de ejemplo con todos los colores
echo -e "GRUPO 0"
echo -e "${negro}Negro${resetc}"
echo -e "${rojo}Rojo${resetc}"
echo -e "${verde}Verde${resetc}"
echo -e "${amarillo}Amarillo${resetc}"
echo -e "${azul}Azul${resetc}"
echo -e "${morado}Morado${resetc}"
echo -e "${celeste}Celeste${resetc}"
echo -e "${blanco}Blanco${resetc}"
echo -e "GRUPO 1"
echo -e "${bnegro}Negro Negrita${resetc}"
echo -e "${brojo}Rojo Negrita${resetc}"
echo -e "${bverde}Verde Negrita${resetc}"
echo -e "${bamarillo}Amarillo Negrita${resetc}"
echo -e "${bazul}Azul Negrita${resetc}"
echo -e "${bmorado}Morado Negrita${resetc}"
echo -e "${bceleste}Celeste Negrita${resetc}"
echo -e "${bblanco}Blanco Negrita${resetc}"
echo -e "GRUPO 2"
echo -e "${fnegro}Fondo Negro${resetc}"
echo -e "${frojo}Fondo Rojo${resetc}"
echo -e "${fverde}Fondo Verde${resetc}"
echo -e "${famarillo}Fondo Amarillo${resetc}"
echo -e "${fazul}Fondo Azul${resetc}"
echo -e "${fmorado}Fondo Morado${resetc}"
echo -e "${fceleste}Fondo Celeste${resetc}"
echo -e "${fblanco}Fondo Blanco${resetc}"
echo -e "GRUPO 3"
echo -e "${snegro}Negro Subrayado${resetc}"
echo -e "${srojo}Rojo Subrayado${resetc}"
echo -e "${sverde}Verde Subrayado${resetc}"
echo -e "${samarillo}Amarillo Subrayado${resetc}"
echo -e "${sazul}Azul Subrayado${resetc}"
echo -e "${smorado}Morado Subrayado${resetc}"
echo -e "${sceleste}Celeste Subrayado${resetc}"
echo -e "${sblanco}Blanco Subrayado${resetc}"
echo -e "GRUPO 4"
echo -e "${hnegro}Negro Alta Intensidad${resetc}"
echo -e "${hrojo}Rojo Alta Intensidad${resetc}"
echo -e "${hverde}Verde Alta Intensidad${resetc}"
echo -e "${hamarillo}Amarillo Alta Intensidad${resetc}"
echo -e "${hazul}Azul Alta Intensidad${resetc}"
echo -e "${hmorado}Morado Alta Intensidad${resetc}"
echo -e "${hceleste}Celeste Alta Intensidad${resetc}"
echo -e "${hblanco}Blanco Alta Intensidad${resetc}"
echo -e "GRUPO 5"
echo -e "${nhnegro}Negro Negrita Alta Intensidad${resetc}"
echo -e "${nhrojo}Rojo Negrita Alta Intensidad${resetc}"
echo -e "${nhverde}Verde Negrita Alta Intensidad${resetc}"
echo -e "${nhamarillo}Amarillo Negrita Alta Intensidad${resetc}"
echo -e "${nhazul}Azul Negrita Alta Intensidad${resetc}"
echo -e "${nhmorado}Morado Negrita Alta Intensidad${resetc}"
echo -e "${nhceleste}Celeste Negrita Alta Intensidad${resetc}"
echo -e "${nhblanco}Blanco Negrita Alta Intensidad${resetc}"
echo -e "GRUPO 6"
echo -e "${fhnegro}Fondo Negro Alta Intensidad${resetc}"
echo -e "${fhrojo}Fondo Rojo Alta Intensidad${resetc}"
echo -e "${fhverde}Fondo Verde Alta Intensidad${resetc}"
echo -e "${fhamarillo}Fondo Amarillo Alta Intensidad${resetc}"
echo -e "${fhazul}Fondo Azul Alta Intensidad${resetc}"
echo -e "${fhmorado}Fondo Morado Alta Intensidad${resetc}"
echo -e "${fhceleste}Fondo Celeste Alta Intensidad${resetc}"
echo -e "${fhblanco}Fondo Blanco Alta Intensidad${resetc}"
echo -e "GRUPO 7"
echo -e "${fnhnegro}Fondo Negro Alta Intensidad Texto Negrita${resetc}"
echo -e "${fnhrojo}Fondo Rojo Alta Intensidad Texto Negrita${resetc}"
echo -e "${fnhverde}Fondo Verde Alta Intensidad Texto Negrita${resetc}"
echo -e "${fnhamarillo}Fondo Amarillo Alta Intensidad Texto Negrita${resetc}"
echo -e "${fnhazul}Fondo Azul Alta Intensidad Texto Negrita${resetc}"
echo -e "${fnhmorado}Fondo Morado Alta Intensidad Texto Negrita${resetc}"
echo -e "${fnhceleste}Fondo Celeste Alta Intensidad Texto Negrita${resetc}"
echo -e "${fnhblanco}Fondo Blanco Alta Intensidad Texto Negrita${resetc}"
